# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'OCAzureContainerRegistry'
            repository: 'dockerwebapp'
            command: 'build'
            Dockerfile: '$(Build.SourcesDirectory)/dotnetdockerapp/dotnet-webapp/Dockerfile'
            buildContext: '$(Build.SourcesDirectory)/dotnetdockerapp'
            tags: '$(tag)'
        - task: Docker@2
          inputs:
            containerRegistry: 'OCAzureContainerRegistry'
            repository: 'dockerwebapp'
            command: push
            tags: '$(tag)'